# 4.1 NumPy ndarray:多维数组对象 

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[-0.85644086, -1.66019215,  1.08942472],
       [ 0.86378376, -0.43829138, -0.46760438]])

In [4]:
data * 10

array([[ -8.56440857, -16.60192153,  10.89424717],
       [  8.6378376 ,  -4.38291375,  -4.67604381]])

In [5]:
data + data

array([[-1.71288171, -3.32038431,  2.17884943],
       [ 1.72756752, -0.87658275, -0.93520876]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

## 4.1.1 生成ndarray

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 4.1.3 NumPy数组算数

In [21]:
# 向量化
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [24]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
# 同尺寸数组之间的比较会得到一个布尔值数组
arr2 = np.array([[0, 4, 1], [7, 2, 12]])

In [27]:
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [28]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

## 基础索引与切片

In [29]:
arr  = np.arange(10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[5]

5

In [32]:
arr[5:8]

array([5, 6, 7])

In [33]:
arr[5:8] = 12

In [34]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
arr_slice = arr[5:8]

In [36]:
arr_slice

array([12, 12, 12])

In [37]:
arr_slice[1] = 12345

In [38]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

## 4.1.4.1 数组的切片索引

In [39]:
arr = np.array([0,1,2,3,4,64, 64, 64, 8,9])

In [40]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [41]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [42]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2d[1,:2]

array([4, 5])

In [46]:
arr2d[:2, 1:] = 0

In [47]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 4.1.5 布尔索引

In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [49]:
data = np.random.randn(7,4)

In [50]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [51]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [52]:
data

array([[-0.604122  , -0.33562335,  0.10710015,  0.59054331],
       [ 1.21269518, -0.6752656 ,  1.30770628, -0.95139062],
       [-0.29976067,  0.17566285, -1.62086535,  1.04656026],
       [-2.42796522,  0.79954214,  1.27911947,  0.25166939],
       [-1.71705532, -0.70275511, -0.33664048,  0.56136469],
       [-1.0654319 ,  0.85035145,  0.029846  , -0.48299126],
       [ 0.10007795, -0.28525016,  0.6738888 , -0.00774783]])

In [53]:
data[names == 'Bob']

array([[-0.604122  , -0.33562335,  0.10710015,  0.59054331],
       [-2.42796522,  0.79954214,  1.27911947,  0.25166939]])

In [54]:
data[names == 'Bob', 2:]

array([[0.10710015, 0.59054331],
       [1.27911947, 0.25166939]])

In [55]:
data[data<0] = 0

In [56]:
data

array([[0.        , 0.        , 0.10710015, 0.59054331],
       [1.21269518, 0.        , 1.30770628, 0.        ],
       [0.        , 0.17566285, 0.        , 1.04656026],
       [0.        , 0.79954214, 1.27911947, 0.25166939],
       [0.        , 0.        , 0.        , 0.56136469],
       [0.        , 0.85035145, 0.029846  , 0.        ],
       [0.10007795, 0.        , 0.6738888 , 0.        ]])

In [57]:
data[names != 'Joe'] = 7

In [58]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.21269518, 0.        , 1.30770628, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.85035145, 0.029846  , 0.        ],
       [0.10007795, 0.        , 0.6738888 , 0.        ]])

## 4.1.6 神奇索引

In [59]:
arr = np.empty((8,4))

In [60]:
for i in range(8):
    arr[i]=i

In [61]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [62]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [63]:
# 传入负值时，将从尾部进行选择
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [64]:
np.arange(32).reshape((8,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

## 4.1.7 数组转置和换轴

In [65]:
arr = np.arange(15).reshape((3,5))

In [66]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [68]:
# 计算矩阵内积
arr = np.random.randn(6,3)

In [69]:
arr

array([[ 0.12435172,  1.51394878,  0.57931944],
       [-0.60643616,  0.50844775, -0.02431314],
       [ 2.23949902,  0.03368622, -0.29144378],
       [-0.41225187,  0.88795907,  0.4891806 ],
       [ 0.72637483, -0.79653924, -0.33521099],
       [-1.74264459, -0.21946359,  0.83330073]])

In [70]:
np.dot(arr.T, arr)

array([[ 9.13296622, -0.60684052, -2.46320578],
       [-0.60684052,  4.02280514,  1.37338226],
       [-2.46320578,  1.37338226,  1.4671958 ]])

In [71]:
## transpose 用于对高维的数组进行置换轴
arr = np.arange(16).reshape((2,2,4))

In [72]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [73]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [74]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [75]:
# swapaxes方法用于对轴进行调整
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])