# 4.2 通用函数：快速的逐元素数组函数

通用函数，也成为ufunc，是一种在ndarray数据中进行逐元素操作的函数，某些简单函数接受一个或多个标量数值，并产生一个或多个标量结果，而通用函数就是对这些简单函数的向量化封装。如sqrt和exp函数。

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
# 二元通用函数
x = np.random.randn(8)

In [8]:
y = np.random.randn(8)

In [9]:
x

array([-0.42770009,  0.48644732,  1.32369883, -0.47374349,  0.06309896,
        0.29350668, -1.6866235 , -0.40176759])

In [10]:
y

array([ 1.5757244 ,  2.03982968, -1.37305665,  0.37534387,  1.11245847,
       -1.43088098, -0.09052074,  0.42437424])

In [11]:
# nmumpy.maximum 逐个元素地将x和y中元素的最大值计算出来
np.maximum(x,y)

array([ 1.5757244 ,  2.03982968,  1.32369883,  0.37534387,  1.11245847,
        0.29350668, -0.09052074,  0.42437424])

In [13]:
arr = np.random.randn(7)*5

In [14]:
arr

array([-3.21883653, -8.63089059, -1.5416469 , -4.14961528,  1.6553606 ,
       -6.90224439,  1.58814168])

**一些通用函数返回多个数组，比如modf，是Python内建函数divmod的向量化版本，返回一个浮点值数组的小数部分和整数部分。**

In [15]:
remainder,whole_part = np.modf(arr)

In [16]:
remainder

array([-0.21883653, -0.63089059, -0.5416469 , -0.14961528,  0.6553606 ,
       -0.90224439,  0.58814168])

In [17]:
whole_part

array([-3., -8., -1., -4.,  1., -6.,  1.])

In [18]:
# 通用函数接收一个可选参数out，允许对数组进行按位置操作
arr

array([-3.21883653, -8.63089059, -1.5416469 , -4.14961528,  1.6553606 ,
       -6.90224439,  1.58814168])

In [20]:
np.sqrt(arr)

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan, 1.28660818,
              nan, 1.26021494])

In [21]:
np.sqrt(arr, arr)

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan,        nan,        nan,        nan, 1.28660818,
              nan, 1.26021494])

In [22]:
arr

array([       nan,        nan,        nan,        nan, 1.28660818,
              nan, 1.26021494])

>还有一些通用函数，一元通用函数、二元通用函数见*Python for data analysis*附表