# pandas入门

## *series*和*DataFrame*

## 5.1.1 Series

series是一种一维的数组型对象，它包含了一个值序列，并包含了数据标签，称为*索引(index)*

In [ ]:
import pandas as pd

**可以传入Python列表来创建Series**

In [49]:
obj = pd.Series([4, 7, -5, 3])

In [50]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [51]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [52]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [53]:
obj2 = pd.Series([4,7,-5,3], index=['d', 'b', 'a', 'c'])

In [54]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [55]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [56]:
obj2['a']

-5

In [57]:
obj2['d']

4

In [58]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [59]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [60]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

可以认为Series是一个长度固定且有序的字典，因为其将索引值和数据值按位置配对。

In [61]:
'b' in obj2

True

**可以使用Series将已经包含在Python字典中的数据生成series**

In [62]:
sdata = {'Ohio':3500, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [63]:
obj3 = pd.Series(sdata)

In [64]:
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

当你把字典传递给series构造函数时，产生的series的索引是已经排序好了的字典键。  
你可以将字典键按照你想要的顺序传递给构造函数，从而使生成的series的索引值符合你的预期。

In [65]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [66]:
obj4 = pd.Series(sdata, index=states) # California不在原数组中，故缺失标记为NaN，'Utah'并不在states中，故被排除

In [67]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

pandas中使用isnull和notnull函数来检查缺失数据。

In [68]:
pd.isnull

<function pandas.core.dtypes.missing.isna(obj)>

In [69]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [70]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

isnull和notnull也是Series的实例方法：

In [71]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [72]:
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [73]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [74]:
obj3+obj4

California         NaN
Ohio            7000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [75]:
obj4.name = 'population'

In [76]:
obj4.index.name = 'state'

In [77]:
obj4

state
California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Series的索引可以通过按位置赋值的方式进行改变。

In [78]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [79]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [80]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## 5.1.2 DataFrame

DataFrame表示的是矩阵的数据表，包含已排序的列集合，每一列可以是不同的值类型(数值，字符串，布尔值等)  
DataFrame是二维的。

构建DataFrame最常用的方法是利用包含**等长度**列表或NnumPy数组的字典来形成DataFrame

In [82]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada','Nevada' ],
       'year':[2000, 2001, 2002, 2001, 2002, 2003],
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [83]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

对于大型的DataFrame，head方法将会只选出头部的五行：

In [84]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

如果你制定了顺序，DataFrame将会按照你的指定的顺序排列：

In [86]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

如果你传的列不在字典中，将会在结果中出现缺失值：

In [87]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'forur', 'five', 'six'])

In [88]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
forur  2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [89]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

DataFrame中的一列，可以按字典型标记或属性那样检索为Series：

In [90]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
forur    Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [91]:
frame2.year

one      2000
two      2001
three    2002
forur    2001
five     2002
six      2003
Name: year, dtype: int64

行也可以通过位置或特殊属性loc进行选取：

In [93]:
frame2. loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

列的引用是可以修改的。例如，空的‘debt’列可以赋值为标量值或值数组：

In [94]:
frame2['debt'] = 16.5

In [95]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
forur  2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [98]:
import numpy as np
frame2['debt'] = np.arange(6.)

In [99]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
forur  2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

当你将列表或数组赋值给一个列时，值的长度必须和DataFrame的长度匹配。如果你将Series赋值给一列时，Series的索引将会按照DataFrame的索引重新排列，并在空缺的地方填充缺失值。

In [100]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [101]:
frame2['debt'] = val

In [102]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
forur  2001  Nevada  2.4   NaN
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

如果被赋值的列并不存在，将会产生一个新的列。del关键字可以像在字典中那样对DataFrame删除列。

在del的例子中，首先增加一列,这一列时布尔值，判断条件是state列是否为‘Ohio’：

In [103]:
frame2['eastern'] = frame2.state == 'Ohio'

In [104]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
forur  2001  Nevada  2.4   NaN    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

frame.eastern无法创建新的列

del可以移除之前新建的列：

In [105]:
del frame2['eastern']

In [106]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
forur  2001  Nevada  2.4   NaN
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

**从DataFrame中选取的是数据的视图**， 而不是**拷贝**。因此，对Series的修改会映射到DataFrame中，如果需要复制，则应显示地使用Series的copy方法。

In [107]:
pop = {'Nevada':{2001:2.4, 2002:2.9}, 'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}

In [108]:
frame3 = pd.DataFrame(pop)

In [109]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

可以使用类似NumPy的方法对DataFrame进行转置操作（调换行和列）：

In [110]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

内部字典的键被联合、排序后形成了结果的索引。如果已经显示指明索引的话，内部字典的键将不会被排序：

In [111]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

包含series的字典也可以用于构造DataFrame：

In [112]:
pdata = {'Ohio':frame3['Ohio'][:-1], 
        'Nevada':frame3['Nevada'][:2]}

In [113]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

如果DataFrame的索引和列拥有name属性，则这些name属性也会被显示：

In [114]:
frame3.index.name = 'year';
frame3.columns.name = 'state'

In [115]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

和Series类似，DataFrame的values属性会将包含在DataFrame中的数据以二维的ndarray形式返回：

In [117]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [118]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 5.1.3 索引对象

pandas中的索引对象是用于存储轴标签和其他元数据的（例如轴名称或标签）。在构造Series或DataFrame时，你所使用的任意数组或标签序列都可以在内部转换为索引对象：

In [119]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [120]:
index = obj.index

In [121]:
index

Index(['a', 'b', 'c'], dtype='object')

In [122]:
index[1:]

Index(['b', 'c'], dtype='object')

索引对象是不可变的，因此用户是无法修改索引对象的。

In [124]:
index[1] = 'd'   # TypeErroe

TypeError: Index does not support mutable operations

In [125]:
labels = pd.Index(np.arange(3))

In [126]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [128]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [129]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [130]:
obj2.index

Int64Index([0, 1, 2], dtype='int64')

In [132]:
obj2.index is labels

True

除了类似数组，索引对象也像是一个固定大小的集合：

In [133]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [135]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [136]:
'Ohio' in frame3.columns

True

In [137]:
2003 in frame3.index

False

与Python集合不同，pandas索引对象可以包含重复标签：

In [138]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [139]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')