# 5.2 基本功能

## 5.2.1 重建索引

reindex是pandas对象的重要方法，该方法用于创建一个符合新索引的新对象。

In [1]:
import pandas as pd

In [2]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [3]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

   Series调用reindex方法时，会将数据按照新的索引进行排列，如果某个索引值之前并不存在，则会引入缺失值：

In [4]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [5]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

对于顺序数据，比如时间序列，在重建索引时可能会需要进行插值或填值。method可选参数允许我们使用诸如ffill等方法在重建索引时插值，ffill方法会将值向前填充：

In [6]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])

In [7]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [9]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

在DataFrame中，reindex可以改变行索引、列索引，也可以同时改变二者。当今传入一个序列时，结果中的行会重建索引：

In [12]:
import numpy as np
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index = ['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [13]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [14]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [15]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

可以使用columns关键字重建索引：

In [16]:
states = ['Texas', 'Utah', 'California']

In [17]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [20]:
frame.loc(['a', 'b', 'c', 'd'], states)

TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

## 5.2.2 轴向上删除条目

drop方法会返回一个含有指示值或轴向上删除值的新对象：

In [21]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [22]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [23]:
new_obj = obj.drop('c')

In [25]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [26]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

在DataFrame中，索引值可以从轴向上删除：

In [27]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [28]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

在调用drop时使用标签序列会根据行标签删除值（轴0）：

In [29]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

你可以通过传递axis=1或axis='columns'来从列表中删除值：

In [31]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [32]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

很多函数，例如drop，会修改Series或DataFrame的尺寸或形状，这些方法直接操作原对象而不返回新对象：

In [33]:
obj.drop('c', inplace=True)

In [34]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

**inplace属性会清除被删除的数据**

## 索引、选择与过滤

Series的索引(obj[...]）与NumPy数组索引的功能类似，只不过Series的索引值可以不仅仅是整数。

In [1]:
import pandas as pd
import numpy as np
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

E:\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [2]:
obj['b']

1.0

In [3]:
obj['a']

0.0

In [4]:
obj[1]

1.0

In [5]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [6]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [7]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

普通的Python切片是不包含尾部的，Series的切片与之不同。

In [8]:
obj['b': 'c']

b    1.0
c    2.0
dtype: float64

使用这些方法时会修改Series相应的部分：

In [9]:
obj['b':'c'] = 5

In [10]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [11]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [13]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [14]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [16]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [17]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [18]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [19]:
data[data['one']<5]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

另一个是使用布尔值DataFrame进行索引，布尔值DataFrame可以是对标量值进行比较产生的：

In [23]:
data < 5 

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [26]:
data[data<5]=0

In [27]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

在上述的例子中，这种索引方式更像是NumPy二维数组。

## 5.2.3.1  使用loc和iloc选择数据

允许你使用轴标签(loc)或整数标签(iloc)以NumPy风格的语法从DataFrame中选出数组的行和列的子集。

In [30]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [32]:
data.iloc[2, [3, 0, 1]]   # 在第三行选择第4(11)，第1(8)，第2(9)

four    11
one      8
two      9
Name: Utah, dtype: int32

In [33]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [34]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [36]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [37]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## 5.2.4 整数索引

In [38]:
ser = pd.Series(np.arange(3.))

In [39]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [41]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [42]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [43]:
ser2[-1]

2.0

In [44]:
ser[:1]

0    0.0
dtype: float64

In [46]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [47]:
ser.iloc[:1]

0    0.0
dtype: float64

## 5.2.5 算术和数据对齐

In [49]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [54]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index=['a', 'c', 'e', 'f', 'g'])

In [55]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [56]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [57]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

没有交叠的标签位置上，内部数据会产生缺失值。缺失值会在后续的算术操作上产生影响。在DataFrame的示例中，行和列都会执行对齐。

In [58]:
df1 = pd.DataFrame(np.arange(9.).reshape(3,3),
                  columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colorado'])

In [59]:
df2 = pd.DataFrame(np.arange(12.).reshape(4,3),
                  columns=list('bde'),
                  index=['Utah','Ohio', 'Texas', 'Oregon'])

In [60]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [61]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

这些对象加在一起，返回一个DataFrame，它的索引、列式每个DataFrame的索引、列的**并集**：

In [64]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [65]:
df1 = pd.DataFrame({'A': [1, 2]})

In [66]:
df2 = pd.DataFrame({'B': [3, 4]})

In [67]:
df1

A
0  1
1  2

In [68]:
df2

B
0  3
1  4

In [69]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

## 5.2.5.1 使用填充值的算数方法

In [75]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns=list('abcd'))

In [76]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns=list('abcde'))

In [77]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [78]:
df2.loc[1, 'b'] = np.nan

In [79]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [80]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [82]:
df1 + df2 # 不重叠的位置会产生NA值

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [84]:
# 在df1上使用add方法，将df2和一个fill_value作为参数传入:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

Series和DataFrame的算数方法：  
这些方法中每一个都有一个以r开头的副本，这些副本方法的参数是翻转的，因此下面两个语句的结果是等价的：
~~~~
add, radd                                加法（+）
sub, rsub                                 减法（-）
div, rdiv                                   除法（/）
floordiv,  rfloodiv                    整除（//）
mul, rmul                                乘法（*） 
pow, rpow                               幂次方（**）
~~~~

## 5.2.5.2 DataFrame和Series间的操作

In [85]:
arr = np.arange(12.).reshape((3,4))

In [86]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [87]:
arr[0]

array([0., 1., 2., 3.])

当我们从arr中减去arr[0]时，减法会在每一行都进行操作，这就是所谓的*广播机制*：

In [89]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [90]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [92]:
series = frame.iloc[0]

In [93]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [94]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

默认情况下，DataFrame和Series的数学操作中会将Series的索引和DataFrame的列进行匹配，并广播倒各行：

In [95]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

如果一个索引值不在DataFrame的列中，也不在Series的索引中，则对象会重建索引并形成联合：

In [98]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [99]:
series2

b    0
e    1
f    2
dtype: int64

In [100]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [101]:
series3 = frame['d']

In [102]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [103]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [104]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [105]:
frame.sub(series3, axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 5.2.6 函数应用和映射

NumPy的通用函数对pandas对象也有效：

In [4]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [5]:
frame

b         d         e
Utah    0.990556  0.868646 -0.421801
Ohio   -1.795252  0.733829 -0.184766
Texas   1.425026  0.112813  1.432826
Oregon -0.923285 -0.592316 -0.773560

In [7]:
np.abs(frame) # 取绝对值

b         d         e
Utah    0.990556  0.868646  0.421801
Ohio    1.795252  0.733829  0.184766
Texas   1.425026  0.112813  1.432826
Oregon  0.923285  0.592316  0.773560

另一个常用的功能是将函数应用到一行或一列的一维数组上。DataFrame的apply方法可以实现这个功能。

In [8]:
f = lambda x: x.max() - x.min()

In [10]:
frame.apply(f) # f会被frame中的每一列调用一次

b    3.220277
d    1.460962
e    2.206386
dtype: float64

In [12]:
# 如果要想在每一行实现调用，就可以将axis=‘columns’传递给apply函数
frame.apply(f, axis='columns')

Utah      1.412357
Ohio      2.529080
Texas     1.320013
Oregon    0.330969
dtype: float64

传递给apply的函数并不一定要返回一个标量值，也可以返回带有多个值的Series：

In [13]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [14]:
frame.apply(f)

b         d         e
min -1.795252 -0.592316 -0.773560
max  1.425026  0.868646  1.432826

加入你想根据frame中的每个浮点数计算一个格式化字符串，可以使用applymap方法：

In [15]:
format = lambda x: '%.2f' % x

In [16]:
frame.applymap(format)

b      d      e
Utah     0.99   0.87  -0.42
Ohio    -1.80   0.73  -0.18
Texas    1.43   0.11   1.43
Oregon  -0.92  -0.59  -0.77

In [17]:
frame['e'].map(format)

Utah      -0.42
Ohio      -0.18
Texas      1.43
Oregon    -0.77
Name: e, dtype: object